"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/

Security: DEBUG=False in production; secure cookie and browser headers configured.
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-m@_w%x%si&_d7*+&2-u3ol=4=n+_lz847@mnls^o-gese099^=')

# SECURITY: Set DEBUG to False in production to avoid exposing tracebacks and debug tools.
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if not DEBUG else ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'bookshelf',
    'relationship_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'LibraryProject.middleware.SecurityHeadersMiddleware',  # XSS filter + CSP headers
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Custom user model
# https://docs.djangoproject.com/en/6.0/topics/auth/customizing/#substituting-a-custom-user-model
AUTH_USER_MODEL = 'bookshelf.CustomUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (user uploads, e.g. profile photos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -----------------------------------------------------------------------------
# HTTPS and Secure Redirects
# -----------------------------------------------------------------------------

# Redirect all HTTP requests to HTTPS. Ensures all traffic uses secure connections.
# Set True in production; set False for local HTTP development.
SECURE_SSL_REDIRECT = True

# HTTP Strict Transport Security (HSTS): instructs browsers to only access the site
# via HTTPS for the specified duration. 31536000 seconds = 1 year.
SECURE_HSTS_SECONDS = 31536000

# Apply HSTS to all subdomains (e.g., api.example.com, www.example.com).
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# Allow inclusion in browser HSTS preload lists for stronger protection.
SECURE_HSTS_PRELOAD = True

# When behind a reverse proxy (Nginx, Apache) that terminates SSL, trust the
# X-Forwarded-Proto header so Django correctly identifies HTTPS requests.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# -----------------------------------------------------------------------------
# Secure Cookies
# -----------------------------------------------------------------------------

# Session cookies are only sent over HTTPS. Prevents session hijacking over HTTP.
SESSION_COOKIE_SECURE = True

# CSRF cookies are only sent over HTTPS. Ensures CSRF protection works over secure connections.
CSRF_COOKIE_SECURE = True

# -----------------------------------------------------------------------------
# Secure Headers (clickjacking, MIME sniffing, XSS)
# -----------------------------------------------------------------------------

# Prevent clickjacking: deny embedding in iframes (X-Frame-Options: DENY).
# Protects against UI redressing attacks.
X_FRAME_OPTIONS = 'DENY'

# Prevent MIME-type sniffing (X-Content-Type-Options: nosniff).
# Stops browsers from interpreting responses as a different content type.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Enable the browser's XSS filtering (X-XSS-Protection header).
# Helps prevent cross-site scripting attacks.
SECURE_BROWSER_XSS_FILTER = True

# Content Security Policy: restrict sources for scripts, styles, etc. to reduce XSS risk.
# Default policy allows same origin and inline (adjust for production).
CSP_DEFAULT_SRC = ("'self'",)
CSP_SCRIPT_SRC = ("'self'",)
CSP_STYLE_SRC = ("'self'", "'unsafe-inline'")
CSP_IMG_SRC = ("'self'", "data:", "https:")
CSP_FONT_SRC = ("'self'",)
CSP_CONNECT_SRC = ("'self'",)
CSP_FRAME_ANCESTORS = ("'none'",)
